assign_issues_by:
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: storage'
  - 'api: storagetransfer'
  - 'api: storageinsights'
  to:
  - GoogleCloudPlatform/cloud-storage-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/cloud-sql-connectors
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - 'api: retail'
  to:
  - chenlei1216
- labels:
  - 'api: cloudtrace'
  - 'api: container'
  - 'api: logging'
  - 'api: monitoring'
  - 'api: clouderrorreporting'
  to:
  - GoogleCloudPlatform/dee-platform-ops
- labels:
  - 'product: appengine flex'
  to:
  - GoogleCloudPlatform/serverless-runtimes
- labels:
  - 'aiplatform'
  - 'api: aiplatform'
  - 'api: vertex-ai'
  to:
  - meteatamel
- labels:
  - 'api: secretmanager'
  to:
  - GoogleCloudPlatform/cloud-secrets-team

assign_issues:
  - GoogleCloudPlatform/dotnet-samples-reviewers

assign_prs_always:
- GoogleCloudPlatform/dotnet-samples-reviewers

assign_prs_by:
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/cloud-sql-connectors
- labels:
  - 'api: storage'
  - 'api: storagetransfer'
  - 'api: storageinsights'
  to:
  - GoogleCloudPlatform/cloud-storage-dpes
- labels:
  - 'api: spanner'
  to:
  - GoogleCloudPlatform/api-spanner-dotnet
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - 'api: retail'
  to:
  - chenlei1216
- labels:
  - 'api: cloudtrace'
  - 'api: container'
  - 'api: logging'
  - 'api: monitoring'
  - 'api: clouderrorreporting'
  to:
  - GoogleCloudPlatform/dee-platform-ops
- labels:
  - 'product: appengine flex'
  to:
  - GoogleCloudPlatform/serverless-runtimes
- labels:
  - 'aiplatform'
  - 'api: aiplatform'
  - 'api: vertex-ai'
  to:
  - meteatamel
- labels:
  - 'api: secretmanager'
  to:
  - GoogleCloudPlatform/cloud-secrets-team
