assign_issues_by:
- labels:
  - 'aiplatform'
  - 'api: aiplatform'
  - 'api: run'
  - 'api: vertex-ai'
  to:
  - meteatamel
- labels:
  - 'product: appengine flex'
  to:
  - GoogleCloudPlatform/serverless-runtimes
- labels:
  - 'api: bigquery'
  - 'api: bigquerydatatransfer'
  - 'api: bigquerystorage'
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/cloud-sql-connectors
- labels:
  - 'api: compute'
  to:
  - GoogleCloudPlatform/cloud-sdk-dotnet-team
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - 'api: clouderrorreporting'
  - 'api: cloudtrace'
  - 'api: container'
  - 'api: logging'
  - 'api: monitoring'
  to:
  - GoogleCloudPlatform/dee-platform-ops
- labels:
  - "api: modelarmor"
  to:
  - GoogleCloudPlatform/cloud-modelarmor-team
- labels:
  - 'api: parametermanager'
  to:
  - GoogleCloudPlatform/cloud-parameters-team
- labels:
  - 'api: pubsub'
  to:
  - GoogleCloudPlatform/cloud-sdk-dotnet-team
- labels:
  - 'api: retail'
  to:
  - chenlei1216
- labels:
  - 'api: secretmanager'
  to:
  - GoogleCloudPlatform/cloud-secrets-team
- labels:
  - 'api: spanner'
  to:
  - GoogleCloudPlatform/api-spanner-dotnet
- labels:
  - 'api: storage'
  - 'api: storageinsights'
  - 'api: storagetransfer'
  to:
  - GoogleCloudPlatform/gcs-sdk-team

assign_issues:
  - GoogleCloudPlatform/dotnet-samples-reviewers

assign_prs_always:
- GoogleCloudPlatform/dotnet-samples-reviewers

assign_prs_by:
- labels:
  - 'aiplatform'
  - 'api: aiplatform'
  - 'api: run'
  - 'api: vertex-ai'
  to:
  - meteatamel
- labels:
  - 'product: appengine flex'
  to:
  - GoogleCloudPlatform/serverless-runtimes
- labels:
  - 'api: bigquery'
  - 'api: bigquerydatatransfer'
  - 'api: bigquerystorage'
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-sdk-dotnet-team
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/cloud-sql-connectors
- labels:
  - 'api: compute'
  to:
  - GoogleCloudPlatform/cloud-sdk-dotnet-team
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - 'api: clouderrorreporting'
  - 'api: cloudtrace'
  - 'api: container'
  - 'api: logging'
  - 'api: monitoring'
  to:
  - GoogleCloudPlatform/dee-platform-ops
- labels:
  - "api: modelarmor"
  to:
  - GoogleCloudPlatform/cloud-modelarmor-team
- labels:
  - 'api: parametermanager'
  to:
  - GoogleCloudPlatform/cloud-parameters-team
- labels:
  - 'api: pubsub'
  to:
  - GoogleCloudPlatform/cloud-sdk-dotnet-team
- labels:
  - 'api: retail'
  to:
  - chenlei1216
- labels:
  - 'api: secretmanager'
  to:
  - GoogleCloudPlatform/cloud-secrets-team
- labels:
  - 'api: spanner'
  to:
  - GoogleCloudPlatform/cloud-sdk-dotnet-team
- labels:
  - 'api: storage'
  - 'api: storageinsights'
  - 'api: storagetransfer'
  to:
  - GoogleCloudPlatform/gcs-sdk-team
