assign_issues_by:
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  - 'api: storage'
  - 'api: spanner'
  to:
  - gforgurups
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/infra-db-dpes
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - 'api: retail'
  to:
  - chenlei1216
- labels:
  - 'api: videostitcher'
  - 'api: livestream'
  - 'api: transcoder'
  to:
  - irataxy

assign_prs_by:
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/infra-db-dpes
- labels:
  - 'api: storage'
  to:
  - GoogleCloudPlatform/cloud-storage-dpes
- labels:
  - 'api: spanner'
  to:
  - GoogleCloudPlatform/api-spanner-dotnet
- labels:
  - 'api: dlp'
  to:
  - GoogleCloudPlatform/googleapis-dlp
- labels:
  - 'api: retail'
  to:
  - chenlei1216
- labels:
  - 'api: videostitcher'
  - 'api: livestream'
  - 'api: transcoder'
  to:
  - irataxy
