# Optional file for deploying to Google App Engine Flexible Environment.
runtime: aspnetcore
env: flex

# Remember - storing secrets in plaintext is potentially unsafe. Consider using
# something like https://cloud.google.com/secret-manager/docs/overview to help keep
# secrets secret.
env_variables:
    DB_USER: <your-username>
    DB_PASS: <your-password>
    DB_NAME: <your-database-name>
    INSTANCE_HOST: cloudsql
    
beta_settings:
    cloud_sql_instances: "<project-name>:<region>:<instance-name>=tcp:1433"