runtime: aspnetcore
env: flex
service: jahoak

runtime_config:
  operating_system: ubuntu22

env_variables:
  TEST_BUCKET: jahoak-bucket
  TEST_OBJECT: DataProtectionProviderKeys.xml
  TEST_KMS_KEY_NAME: projects/jahoak-test/locations/global/keyRings/dataprotectionprovider/cryptoKeys/key

